### PR TITLE
chore: backport #93 to release

### PR DESCRIPTION
**Pull request by gitferry**

### CODE REVIEW

**Comment by KonradStaniec** [comment]
Hmm this seems like to have to many commits. Did you follow standard procedure ie.
1. create new `backport_branch` from `release/v0.10.x` branch
2. cherry pick the commit that was already merged to `main` - https://github.com/babylonlabs-io/babylon/commit/22f92830cf5328304791d383f470e1c8d027c5a0 to this branch
3. making pr from the `backport_branch` to `release/v0.10.x`
?

**Comment by SebastianElvis** [comment]
hmm looks like https://github.com/babylonlabs-io/babylon/pull/93 is merged via merge commit :rofl:

**Comment by gitferry** [comment]
ops, I thought merge commit is disabled?

**Comment by KonradStaniec** [comment]
yup merge commits are disabled,  I see that #93 is merged via this commit - https://github.com/babylonlabs-io/babylon/commit/22f92830cf5328304791d383f470e1c8d027c5a0

**Comment by gitferry** [comment]
> Hmm this seems like to have to many commits. Did you follow standard procedure ie.
> 
> 1. create new `backport_branch` from `release/v0.10.x` branch
> 2. cherry pick the commit that was already merged to `main` - [22f9283](https://github.com/babylonlabs-io/babylon/commit/22f92830cf5328304791d383f470e1c8d027c5a0) to this branch
> 3. making pr from the `backport_branch` to `release/v0.10.x`
>    ?

Created PR #100 that follows the above

**Pull request closed without merging**
